#!/bin/bash

DAEMON="/sbin/spindownd"
STATUSPATH="/dev/shm/spindown.status"
CONFPATH="/etc/spindown.conf"
PIDFILE="/var/run/spindownd.pid"

. /lib/lsb/init-functions

# echo's the string and then the amount of spaces needed to fill it till length
# $1 the string
# $2 the desired length
spaces() {
    declare -i i
    declare -i diff
    diff=$2-${#1}

    #at least one space between values
    if [ $diff -lt 1 ]; then
        diff=1
    fi

    #print the string
    echo -n $1

    #print the remaining spaces
    i=0
    while [ $i -lt $diff ]; do
        echo -n " "
        i=$i+1
    done
}

#prints table with status about the disks
status() {
    #print the header of the table
    spaces "name" 15
    spaces "watched" 15
    spaces "active" 15
    spaces "idle-time" 15
    spaces "spindown-time" 15
    echo ""

    #build the rows with disks
    declare -i i
    i=0
    for line in `cat $STATUSPATH`; do
        remainder=`expr $i % 5`
        if [ $remainder -eq 0 -a $i -ne 0 ]; then
            echo ""
            spaces $line 15
        else
            spaces $line 15
        fi

        i=$i+1
    done

    echo ""

    exit 0
}

case "$1" in
    "start")
        log_daemon_msg "Starting disk spindown daemon" "spindownd"
        start_daemon -p $PIDFILE $DAEMON -d -s $STATUSPATH -c $CONFPATH -p $PIDFILE
        log_end_msg $?

        exit $?
        ;;

    "stop")
        log_daemon_msg "Stopping disk spindown daemon" "spindownd"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?

        exit $?
        ;;

    "status")
        if status_of_proc -p $PIDFILE $DAEMON spindown; then
            echo -n
        else
            exit 1
        fi

        killproc -p $PIDFILE $DAEMON -PIPE
        echo "`status`"

        exit 0
        ;;

    "restart"|"condrestart")
        $0 stop
        $0 start

        exit $?
        ;;

    "reload")
        log_daemon_msg "Reloading disk spindown daemon" "spindownd"
        killproc -p $PIDFILE $DAEMON -HUP
        log_end_msg $?

        exit $?
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
