#!/bin/bash

DAEMON="/sbin/spindownd"
STATUSPATH="/dev/shm/spindown.status"
CONFPATH="/etc/spindown.conf"

. /lib/lsb/init-functions

# echo's the string and then the amount of spaces needed to fill it till length
# $1 the string
# $2 the desired length
spaces() {

  declare -i i
  declare -i diff
  diff=$2-${#1}

  #at least one space between values
  if [ $diff -lt 1 ]; then
    diff=1
  fi

  #print the string
  echo -n $1

  #print the remaining spaces
  i=0
  while [ $i -lt $diff ]; do
    echo -n " "
    i=$i+1
  done

}

#prints table with status about the disks
status() {

    if [ $DEBUG ]; then
	echo
    else
	if status_of_proc $DAEMON spindown; then
	    echo -n
	else
	    exit 1
	fi
    fi

    #print the header of the table
    spaces "name" 15
    spaces "watched" 15
    spaces "active" 15
    spaces "idle-time" 15
    spaces "spindown-time" 15
    echo ""

    #build the rows with disks
    declare -i i
    i=0
    for line in `cat $STATUSPATH`; do
	remainder=`expr $i % 5`
	if [ $remainder -eq 0 -a $i -ne 0 ]; then
	echo ""
	spaces $line 15
	else
	spaces $line 15
	fi

	i=$i+1
    done

    echo ""

    exit 0
}

start() {
    log_daemon_msg "Starting disk spindown daemon" "spindownd"
    start_daemon $DAEMON -d -f $STATUSPATH -c $CONFPATH
    log_end_msg $?
}

stop() {
    log_daemon_msg "Stopping disk spindown daemon" "spindownd"
    killproc $DAEMON
    log_end_msg $?
}

reload() {
    log_daemon_msg "Reloading disk spindown daemon" "spindownd"
    killproc $DAEMON -hup
    log_end_msg $?
}

case "$1" in
  "start")
        start
        ;;
  "stop")
        stop
        ;;
  "status")
        #by outputting it like this it all appears on the screen in one time
        echo "`status`"
        ;;
  "restart"|"condrestart")
        stop
        start
        ;;
  "reload")
        reload
        ;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
