#!/bin/bash

DAEMON="/sbin/spindownd"
STATUSPATH="/dev/shm/spindown.status"
CONFPATH="/etc/spindown.conf"
PIDFILE="/var/run/spindownd.pid"

. /lib/lsb/init-functions

#prints table with status about the disks
status() {
    #print the header of the table
	printf "%-5s %10s %10s %15s %20s\n" name watched active idle-time spindown-time

	while read line; do

		printf "%-5s %10s %10s %15s %20s\n" $line

	done < $STATUSPATH

    exit 0
}

case "$1" in
    "start")
        log_daemon_msg "Starting disk spindown daemon" "spindownd"
        start_daemon -p $PIDFILE $DAEMON -d -s $STATUSPATH -c $CONFPATH -p $PIDFILE
        log_end_msg $?

        exit $?
        ;;

    "stop")
        log_daemon_msg "Stopping disk spindown daemon" "spindownd"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?

        exit $?
        ;;

    "status")
        if status_of_proc -p $PIDFILE $DAEMON spindown; then
            echo -n
        else
            exit 1
        fi

        killproc -p $PIDFILE $DAEMON -PIPE
        echo "`status`"

        exit 0
        ;;

    "restart"|"condrestart")
        $0 stop
        $0 start

        exit $?
        ;;

    "reload")
        log_daemon_msg "Reloading disk spindown daemon" "spindownd"
        killproc -p $PIDFILE $DAEMON -HUP
        log_end_msg $?

        exit $?
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
